/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_blinkenlight_api.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static rpc_blinkenlight_api_getinfo_res *
_rpc_blinkenlight_api_getinfo_1 (void  *argp, struct svc_req *rqstp)
{
	return (rpc_blinkenlight_api_getinfo_1_svc(rqstp));
}

static rpc_blinkenlight_api_getpanelinfo_res *
_rpc_blinkenlight_api_getpanelinfo_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (rpc_blinkenlight_api_getpanelinfo_1_svc(*argp, rqstp));
}

static rpc_blinkenlight_api_getcontrolinfo_res *
_rpc_blinkenlight_api_getcontrolinfo_1 (rpc_blinkenlight_api_getcontrolinfo_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_blinkenlight_api_getcontrolinfo_1_svc(argp->arg1, argp->arg2, rqstp));
}

static rpc_blinkenlight_api_setpanel_controlvalues_res *
_rpc_blinkenlight_api_setpanel_controlvalues_1 (rpc_blinkenlight_api_setpanel_controlvalues_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_blinkenlight_api_setpanel_controlvalues_1_svc(argp->arg1, argp->valuelist, rqstp));
}

static rpc_blinkenlight_api_controlvalues_struct *
_rpc_blinkenlight_api_getpanel_controlvalues_1 (u_int  *argp, struct svc_req *rqstp)
{
	return (rpc_blinkenlight_api_getpanel_controlvalues_1_svc(*argp, rqstp));
}

static rpc_param_result_struct *
_rpc_param_get_1 (rpc_param_cmd_get_struct  *argp, struct svc_req *rqstp)
{
	return (rpc_param_get_1_svc(*argp, rqstp));
}

static rpc_param_result_struct *
_rpc_param_set_1 (rpc_param_cmd_set_struct  *argp, struct svc_req *rqstp)
{
	return (rpc_param_set_1_svc(*argp, rqstp));
}

static rpc_test_cmdstatus_struct *
_rpc_test_data_to_server_1 (rpc_test_data_struct  *argp, struct svc_req *rqstp)
{
	return (rpc_test_data_to_server_1_svc(*argp, rqstp));
}

static rpc_test_data_struct *
_rpc_test_data_from_server_1 (rpc_test_cmdstatus_struct  *argp, struct svc_req *rqstp)
{
	return (rpc_test_data_from_server_1_svc(*argp, rqstp));
}

void
blinkenlightd_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		u_int rpc_blinkenlight_api_getpanelinfo_1_arg;
		rpc_blinkenlight_api_getcontrolinfo_1_argument rpc_blinkenlight_api_getcontrolinfo_1_arg;
		rpc_blinkenlight_api_setpanel_controlvalues_1_argument rpc_blinkenlight_api_setpanel_controlvalues_1_arg;
		u_int rpc_blinkenlight_api_getpanel_controlvalues_1_arg;
		rpc_param_cmd_get_struct rpc_param_get_1_arg;
		rpc_param_cmd_set_struct rpc_param_set_1_arg;
		rpc_test_data_struct rpc_test_data_to_server_1_arg;
		rpc_test_cmdstatus_struct rpc_test_data_from_server_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RPC_BLINKENLIGHT_API_GETINFO:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_rpc_blinkenlight_api_getinfo_res;
		local = (char *(*)(char *, struct svc_req *)) _rpc_blinkenlight_api_getinfo_1;
		break;

	case RPC_BLINKENLIGHT_API_GETPANELINFO:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_rpc_blinkenlight_api_getpanelinfo_res;
		local = (char *(*)(char *, struct svc_req *)) _rpc_blinkenlight_api_getpanelinfo_1;
		break;

	case RPC_BLINKENLIGHT_API_GETCONTROLINFO:
		_xdr_argument = (xdrproc_t) xdr_rpc_blinkenlight_api_getcontrolinfo_1_argument;
		_xdr_result = (xdrproc_t) xdr_rpc_blinkenlight_api_getcontrolinfo_res;
		local = (char *(*)(char *, struct svc_req *)) _rpc_blinkenlight_api_getcontrolinfo_1;
		break;

	case RPC_BLINKENLIGHT_API_SETPANEL_CONTROLVALUES:
		_xdr_argument = (xdrproc_t) xdr_rpc_blinkenlight_api_setpanel_controlvalues_1_argument;
		_xdr_result = (xdrproc_t) xdr_rpc_blinkenlight_api_setpanel_controlvalues_res;
		local = (char *(*)(char *, struct svc_req *)) _rpc_blinkenlight_api_setpanel_controlvalues_1;
		break;

	case RPC_BLINKENLIGHT_API_GETPANEL_CONTROLVALUES:
		_xdr_argument = (xdrproc_t) xdr_u_int;
		_xdr_result = (xdrproc_t) xdr_rpc_blinkenlight_api_controlvalues_struct;
		local = (char *(*)(char *, struct svc_req *)) _rpc_blinkenlight_api_getpanel_controlvalues_1;
		break;

	case RPC_PARAM_GET:
		_xdr_argument = (xdrproc_t) xdr_rpc_param_cmd_get_struct;
		_xdr_result = (xdrproc_t) xdr_rpc_param_result_struct;
		local = (char *(*)(char *, struct svc_req *)) _rpc_param_get_1;
		break;

	case RPC_PARAM_SET:
		_xdr_argument = (xdrproc_t) xdr_rpc_param_cmd_set_struct;
		_xdr_result = (xdrproc_t) xdr_rpc_param_result_struct;
		local = (char *(*)(char *, struct svc_req *)) _rpc_param_set_1;
		break;

	case RPC_TEST_DATA_TO_SERVER:
		_xdr_argument = (xdrproc_t) xdr_rpc_test_data_struct;
		_xdr_result = (xdrproc_t) xdr_rpc_test_cmdstatus_struct;
		local = (char *(*)(char *, struct svc_req *)) _rpc_test_data_to_server_1;
		break;

	case RPC_TEST_DATA_FROM_SERVER:
		_xdr_argument = (xdrproc_t) xdr_rpc_test_cmdstatus_struct;
		_xdr_result = (xdrproc_t) xdr_rpc_test_data_struct;
		local = (char *(*)(char *, struct svc_req *)) _rpc_test_data_from_server_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}
