/** \file
 *  This C header file was generated by $ANTLR version 3.5.1
 *
 *     -  From the grammar source file : /home/joerg/retrocmp/blinkenbone/projects/07.1_blinkenlight_server/panel_config_grammar/blinkenlight_panel_config.g
 *     -                            On : 2016-03-26 09:26:02
 *     -                for the parser : blinkenlight_panel_configParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
blinkenlight_panel_configParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pblinkenlight_panel_configParser, which is returned from a call to blinkenlight_panel_configParserNew().
 *
 * The methods in pblinkenlight_panel_configParser are  as follows:
 *
 *  - 
 void
      pblinkenlight_panel_configParser->definition_list(pblinkenlight_panel_configParser)
 *  - 
 void
      pblinkenlight_panel_configParser->definition(pblinkenlight_panel_configParser)
 *  - 
 void
      pblinkenlight_panel_configParser->variable_definition(pblinkenlight_panel_configParser)
 *  - 
 void
      pblinkenlight_panel_configParser->panel_definition(pblinkenlight_panel_configParser)
 *  - 
 void
      pblinkenlight_panel_configParser->panel_parameter(pblinkenlight_panel_configParser)
 *  - 
 void
      pblinkenlight_panel_configParser->control_definition(pblinkenlight_panel_configParser)
 *  - 
 void
      pblinkenlight_panel_configParser->control_parameter(pblinkenlight_panel_configParser)
 *  - 
 void
      pblinkenlight_panel_configParser->register_wiring_list(pblinkenlight_panel_configParser)
 *  - 
 void
      pblinkenlight_panel_configParser->register_wiring(pblinkenlight_panel_configParser)
 *  - 
 void
      pblinkenlight_panel_configParser->register_wiring_parameter(pblinkenlight_panel_configParser)
 *  - 
 blinkenlight_panel_configParser_string_expr_return
      pblinkenlight_panel_configParser->string_expr(pblinkenlight_panel_configParser)
 *  - 
 long
      pblinkenlight_panel_configParser->unsigned_int_expr(pblinkenlight_panel_configParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_blinkenlight_panel_configParser_H
#define _blinkenlight_panel_configParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct blinkenlight_panel_configParser_Ctx_struct blinkenlight_panel_configParser, * pblinkenlight_panel_configParser;



#include <string.h>

#include "config.h"
#include "namevaluelist.h"

// global panel config
extern blinkenlight_panel_list_t *blinkenlight_panel_list ;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif
typedef struct blinkenlight_panel_configParser_string_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    char  * value;
}
    blinkenlight_panel_configParser_string_expr_return;





/** Context tracking structure for 
blinkenlight_panel_configParser

 */
struct blinkenlight_panel_configParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     void
     (*definition_list)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     void
     (*definition)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     void
     (*variable_definition)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     void
     (*panel_definition)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     void
     (*panel_parameter)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     void
     (*control_definition)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     void
     (*control_parameter)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     void
     (*register_wiring_list)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     void
     (*register_wiring)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     void
     (*register_wiring_parameter)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     blinkenlight_panel_configParser_string_expr_return
     (*string_expr)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);

     long
     (*unsigned_int_expr)	(struct blinkenlight_panel_configParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct blinkenlight_panel_configParser_Ctx_struct * ctx);
    void	    (*free)   (struct blinkenlight_panel_configParser_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pblinkenlight_panel_configParser blinkenlight_panel_configParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pblinkenlight_panel_configParser blinkenlight_panel_configParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__74      74
#define T__75      75
#define T__76      76
#define T__77      77
#define T__78      78
#define T__79      79
#define T__80      80
#define ACTIVE_HIGH      4
#define ACTIVE_LOW      5
#define BITLEN      6
#define BITS      7
#define BITS_MIRRORED      8
#define BLINKENBUS_WIRING      9
#define BOARD      10
#define CHAR      11
#define COMMENT      12
#define CONTROL      13
#define DEFAULT      14
#define DIGITS      15
#define ENCODING      16
#define ENCODING_BINARY      17
#define ENCODING_BITPOSITION      18
#define ESC_SEQ      19
#define FMAX      20
#define HEX_DIGIT      21
#define HEX_DIGITS      22
#define IDENTIFIER      23
#define IN0      24
#define IN1      25
#define IN10      26
#define IN11      27
#define IN12      28
#define IN13      29
#define IN14      30
#define IN2      31
#define IN3      32
#define IN4      33
#define IN5      34
#define IN6      35
#define IN7      36
#define IN8      37
#define IN9      38
#define INFO      39
#define LEVELS      40
#define NAME      41
#define OCTAL_DIGITS      42
#define OCTAL_ESC      43
#define OUT0      44
#define OUT1      45
#define OUT10      46
#define OUT11      47
#define OUT12      48
#define OUT13      49
#define OUT14      50
#define OUT2      51
#define OUT3      52
#define OUT4      53
#define OUT5      54
#define OUT6      55
#define OUT7      56
#define OUT8      57
#define OUT9      58
#define PANEL      59
#define RADIX      60
#define REGISTER      61
#define REGISTER_WIRING      62
#define STRING      63
#define TYPE      64
#define TYPE_KNOB      65
#define TYPE_LAMP      66
#define TYPE_OTHERINPUT      67
#define TYPE_OTHEROUTPUT      68
#define TYPE_POINTER      69
#define TYPE_SWITCH      70
#define UNICODE_ESC      71
#define VALUE_BIT_OFFSET      72
#define WS      73
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for blinkenlight_panel_configParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
