/*
 * msg_proc.c: implementation of the remote procedure "printmessage"
 */
#include <stdio.h>
#include <rpc/rpc.h> /* always needed */
#include "msgrpc.h" /* need this too: will be generated by rpcgen */
/*
 * Remote version of "printmessage"
 */
// int * printmessage_1(my2params *argp, struct svc_req *rqstp)
int *
printmessage_1_svc(my2params *params, struct svc_req *rqstp)
{
	static int result; /* must be static! */
	FILE *f;
	f = fopen("/dev/tty", "w"); // print to terminal of server process
	if (f == NULL)
	{
		result = 0;
		return (&result);
	}
	fprintf(f, "%s (%d times!)\n", params->message, params->counter);
	fclose(f);
	result = 1;
	return (&result);
}
